### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by tr3iscool** [galehouse5/skribbl-io-autodraw#2]
How do i install this?

**Comment by GlitchMasta47** [comment]
# Next time, I reccomend this fine website
[https://www.google.com/](https://www.google.com/)

# How to ~~pack and~~ load an extension in Google Chrome
0. Download a ZIP of this GitHub repo (and extract it to a folder somewhere)
1. Go to your Extensions page (chrome://extensions)
2. Enable developer mode.
![Developer mode checkbox](https://i.hackforjes.us/i/vvh59l70.png)
3. Press the "Load unpacked" button
![Load unpacked button](https://i.hackforjes.us/i/x5ht7v7d.png)
4. In the file dialog box that appears, select the folder where your zip was extracted
5. Press OK and the extension is successfully installed, you should now see it in your extensions list
![Extension showing in extensions list](https://i.hackforjes.us/i/zpgefbex.png)

Google Chrome will every so often nag you about removing the extension because it could be "harmful."
You can safely ignore these messages.
![](https://i.hackforjes.us/i/w5z6lzpr.png)

## Or...
If you don't want to go through that mess, or you aren't able to:
- Download a ZIP file of the archive
- Enable developer mode
- Find your extensions page

I will figure out a way to pack the extension and it not warn you with this error:
!["Apps, extensions, and user scripts cannot be added from this website"](https://i.hackforjes.us/i/4sn3i09y.png)
and let you know. Until then, load it unpacked and ignore the warnings.

**Comment by RandomEVB** [comment]
How do i get it to work

**Comment by tr3iscool** [comment]
> How do i get it to work

Drag a image (downloaded) on it

**Comment by Wubbalubbadubdub4** [comment]
how do i make it join

**Comment by GlitchMasta47** [comment]
@Wubbalubbadubdub4 What do you mean by "make it join"

You join a game with this browser extension installed, drag an image onto the canvas when it's your turn, and that's it.

**Comment by pabbie** [comment]
Is there anyways to make it faster? lol

**Comment by DecrepitHuman** [comment]
Hi, When I drag the imagine into the canvas, chrome redirects me to the opened file

**Comment by GlitchMasta47** [comment]
> Hi, When I drag the imagine into the canvas, chrome redirects me to the opened file

I wasn't able to reproduce this using the latest version available on the Chrome Webstore. Please make a new issue if you still need help.

**Comment by Cuocake1234** [comment]
I cant download

**Comment by Cuocake1234** [comment]
Hi, i downloaded this but it wont let me paste an image in the skribbl io draw area that i copied bc im on phone

**Comment by GlitchMasta47** [comment]
You need to drag and drop the image onto the canvas. I'm not confident that this extension is made for phones, and honestly I didn't even know that was possible. Please try to drag and drop instead of paste, and if your phone doesn't support that then please try to use a computer as this extension wasn't meant for phones.
