### ISSUE TITLE
Slow At Drawing

### ISSUE THREAD

**Issue by MantisGalaxy** [galehouse5/skribbl-io-autodraw#21]
So, I was trolling my friends but it was pretty slow and the drawing time ended

**Comment by GlitchMasta47** [comment]
Usually higher resolution images take longer to be drawn. If you're able to find lower quality images you should be able to draw faster by using those instead.

**Comment by galehouse5** [comment]
Drawing rate is limited by the skribbl.io servers, which kick you from the room when you send draw commands too quickly. Try selecting a simpler image. Clipart is best. Photographs are bad because they have lots of detail that requires lots of draw commands.

![image](https://user-images.githubusercontent.com/1687988/81370419-198e4c80-90c3-11ea-9e15-3422752ce0a2.png)
