### ISSUE TITLE
Is this normal? Autodraw looks like shid

### ISSUE THREAD

**Issue by A-Random-Lantern** [galehouse5/skribbl-io-autodraw#6]
![image](https://user-images.githubusercontent.com/23159237/51805270-8caae100-2239-11e9-9c17-700b46379463.png)

**Comment by A-Random-Lantern** [comment]
for this one it looked fine, but for other pictures it looks unfinished and bad, couldnt tell what it was myself

**Comment by galehouse5** [comment]
We could probably get something closer to this:

![image](https://user-images.githubusercontent.com/1687988/51814566-e3d8a200-2289-11e9-8a4a-2a6955954712.png)

The limiting factor is the rate skribbl.io servers process line draw commands. It's somewhere between 5,000 and 10,000 per minute. The image above contains 30,000 pixels so the naive method of using one line draw command per pixel would take 3 to 6 minutes.

That's why we draw this:

![image](https://user-images.githubusercontent.com/1687988/51815194-51d29880-228d-11e9-8d6a-65baad99f094.png)

It's only 4,800 pixels. Also, we draw multiple adjacent pixels of the same color using a single line draw command so it's even fewer draw commands. We'll have to do better to draw the level of detail in the first image in the 80 second time limit, though.

I can't promise anything, but I'll experiment with some ideas.

**Comment by FreePvp** [comment]
we need blues and other colors

**Comment by galehouse5** [comment]
Now drawing like this:

![image](https://user-images.githubusercontent.com/1687988/59983002-59059480-95e8-11e9-881a-cc8b36d8e186.png)

It took over 2 minutes and 15k commands to draw that image. The best way to reduce that is by selecting a simpler image.
